### ISSUE TITLE
Choreography doesn't work after update.

### ISSUE THREAD

**Issue by SolsticeSpectrum** [Darxeal/Choreography#1]
No idea what is going on. No actual errors in the console but when trying to run any choreography even from other creators it just doesn't work. It spawns bots and they are trying to play regular match instead. Might be Hivemind issue actually so I already reported.

**Comment by ViliamVadocz** [comment]
Let's continue the discussion [here](https://github.com/ViliamVadocz/Hivemind/issues/2), since that's where I answered back first.
